log: ""
host: ""
port: ""
workdir: ""
broken_gap: 10
cmds:
 - 
  cmd: test/test
  output: ""
 #- 
 # cmd: "test/cron_test"
 # args: 
 #  - "ak"
 #  - "av"
 # output: "test/cron_test.log"
 # cron: "* * * * * * *"
 - 
  cmd: "test/cron_test"
  args: 
   - "ak2"
   - "av2"
  output: "test/cron.test.log"
  cron: "* * * * *"
