log: ""
port: ""
broken_gap: 10
cmds:
 - 
  cmd: test/test_darwin
  args: 
   - ak
   - av
  output: test/test.log 
 - 
  cmd: "test/test"
  args: 
   - "ak"
   - "av"
  output: "test/test.log"
  cron: "* * * * *"
   
